name: mood_habit_tracking_tfg
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-22.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  table_calendar: ^3.0.9
  fl_chart: ^0.60.0
  percent_indicator: ^4.2.3
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  path: ^1.8.3
  share_plus: ^7.0.2
  #hive database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # hive database generators
  build_runner: ^2.3.3
  hive_generator: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/questionnaire.json
    - assets/password.json
